/* eslint-disable react-refresh/only-export-components */
import type { Metadata } from 'next';

import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';
import { roboto } from '@/fonts';
import '@/styles/globals.css';
import '@/styles/reset.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} container`}>
        <Header />
        <main className="hero">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
