/* eslint-disable react-refresh/only-export-components */
import type { Metadata } from 'next';

import Footer from '@/components/footer/Footer';
import Header from '@/components/header/Header';
import { roboto } from '@/fonts';
import '@/styles/globals.css';
import '@/styles/reset.css';
import Providers from '@/utils/provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} container`}>
        <Providers>
          <Header />
          <main className="hero">{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
