-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- Kullanıcılar (User) tablosunu oluştur
-- CREATE TABLE users (
--     user_id SERIAL PRIMARY KEY,
--     username VARCHAR(255) NOT NULL,
--     email VARCHAR(255) NOT NULL UNIQUE,
--     created_at TIMESTAMP DEFAULT NOW()
-- );
--
-- -- Gönderiler (Post) tablosunu oluştur
-- CREATE TABLE posts (
--     post_id SERIAL PRIMARY KEY,
--     user_id INT REFERENCES users(user_id),
--     title VARCHAR(255) NOT NULL,
--     content TEXT NOT NULL,
--     created_at TIMESTAMP DEFAULT NOW(),
--     updated_at TIMESTAMP,
--     CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE
-- );
--
-- -- Yorumlar (Comment) tablosunu oluştur
-- CREATE TABLE comments (
--     comment_id SERIAL PRIMARY KEY,
--     user_id INT REFERENCES users(user_id),
--     post_id INT REFERENCES posts(post_id),
--     content TEXT NOT NULL,
--     created_at TIMESTAMP DEFAULT NOW(),
--     CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users(user_id) ON DELETE CASCADE,
--     CONSTRAINT fk_post FOREIGN KEY (post_id) REFERENCES posts(post_id) ON DELETE CASCADE
-- );
